spring:

  profiles:
    active: local

  application:
    name: api-gateway



  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect


server:
  port: 8080
